# -*- coding: utf-8 -*-
"""Scraping_Amazon_using_Jupyter_Notebook.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gxuI-WBYCP2UYBBUfyTG8SzVPokP1ypZ
"""

try:
    import scrapy
except:
    !pip install scrapy
    import scrapy
from scrapy.crawler import CrawlerProcess

"""frist install scrapy and import it

Using following command to create new scrapy project
"""

!scrapy startproject amazon_scraping

"""Move to scrapy directory"""

# Commented out IPython magic to ensure Python compatibility.
# %cd amazon_scraping/

"""create spider"""

!scrapy genspider amazon_spider amazon.com

!pwd

# Commented out IPython magic to ensure Python compatibility.
# %cd amazon_scraping/

!pwd

"""install scrapy user agents

do changes in amazon.spider.py (spyder file) file, items.py (items we going to scrap) and setting.py  file
"""

!pip install scrapy-user-agents

"""run our program"""

!scrapy crawl amazon_spider

!pwd

!zip -r /content/amazon_scraping/file.zip /content/amazon_scraping

from google.colab import files
files.download("/content/amazon_scraping/file.zip")

